version: '3'
services:
  devops:
    build: .
    ports:
      - "3000:3000"
  mysql: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    ports:
      - "3306:3306"

