version: '3'
services:
  mysql:
    container_name: mysql-devops
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  devops:
    container_name: devops-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=devops
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops
    command: ["sh", "-c", "while ! timeout 1 bash -c 'cat < /dev/null > /dev/tcp/mysql-devops/3306'; do sleep 1; done; node app.mjs"]
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - devops
  certbot:
    image: certbot/certbot
    command: certonly --standalone --preferred-challenges http --agree-tos --email devops_com619@hotmail.com -d com619trial.uksouth.cloudapp.azure.com
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"


volumes:
  mysql-data:
  certbot-etc:
  certbot-var:
