name: NodeJS Github Action

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout the repository
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      - name: Rebuild bcrypt
        run: npm rebuild --update-binary bcrypt
      - name: Adjust permissions for jest
        run: chmod +x ./node_modules/.bin/jest
      - name: npm test
        run: npm test

  publish_to_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:tag .
          docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:tag

  deploy:
    needs: publish_to_docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H com619trial.uksouth.cloudapp.azure.com >> ~/.ssh/known_hosts
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@com619trial.uksouth.cloudapp.azure.com 'bash -s' < deploy_script.sh
